import 'package:flutter/foundation.dart';
import 'package:flutter_drivekit_trip_simulator_ios/src/adapter.dart';
import 'package:flutter_drivekit_trip_simulator_ios/src/trip_simulator_api.g.dart';
import 'package:flutter_drivekit_trip_simulator_platform_interface/flutter_drivekit_trip_simulator_platform_interface.dart';

/// The iOS implementation of [DrivekitTripSimulatorPlatform].
class DrivekitTripSimulatorIOS extends DrivekitTripSimulatorPlatform {
  /// Creates a new instance of [DrivekitTripSimulatorIOS].
  /// The optional [iosTripSimulatorApi] parameter is used for
  /// dependency injection in tests.
  DrivekitTripSimulatorIOS({IOSTripSimulatorApi? iosTripSimulatorApi})
      : iosTripSimulatorApi = iosTripSimulatorApi ?? IOSTripSimulatorApi();

  /// Registers this class as the default instance of
  /// [DrivekitTripSimulatorPlatform]
  static void registerWith() {
    DrivekitTripSimulatorPlatform.instance = DrivekitTripSimulatorIOS();
  }

  /// The instance of [IOSTripSimulatorApi], a class that provides access to the
  /// native methods via a method channel generated by pigeon.
  @visibleForTesting
  final IOSTripSimulatorApi iosTripSimulatorApi;

  @override
  Future<String> getPlatformName() => iosTripSimulatorApi.getPlatformName();

  @override
  Future<void> start(PresetTrip presetTrip) =>
      iosTripSimulatorApi.start(presetTrip.toPigeonImplementation());

  @override
  Future<void> stop() => iosTripSimulatorApi.stop();
}
