name: flutter_drivekit_trip_analysis
description: This is the Flutter plugin for DriveQuant's DriveKit Trip Analysis component.
version: 1.2.1
homepage: https://www.drivequant.com/
repository: https://github.com/DriveQuantPublic/flutter-drivekit/tree/main/packages/drivekit_trip_analysis/flutter_drivekit_trip_analysis

environment:
  sdk: ^3.4.0
  flutter: '>=1.20.0'

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_drivekit_trip_analysis_android
      ios:
        default_package: flutter_drivekit_trip_analysis_ios

dependencies:
  flutter:
    sdk: flutter
  flutter_drivekit_trip_analysis_android: ^1.2.1
  flutter_drivekit_trip_analysis_ios: ^1.2.1
  flutter_drivekit_trip_analysis_platform_interface: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
