name: drivekit_example
description: Demonstrates how to use the drivekit SDK.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_drivekit_core: ^0.0.2
  flutter_drivekit_trip_analysis: ^0.0.2
  flutter_drivekit_trip_simulator: ^0.0.2
  gap: ^3.0.1
  permission_handler: ^11.3.1
  sliver_tools: ^0.2.12

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
