name: drivekit_core_example
description: Demonstrates how to use the drivekit_core plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_drivekit_core:
    path: ../
  flutter_drivekit_trip_analysis:
    path: ../../../drivekit_trip_analysis/flutter_drivekit_trip_analysis
  gap: ^3.0.1
  permission_handler: ^11.3.1
  sliver_tools: ^0.2.12

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
