name: flutter_drivekit

packages:
  - packages/drivekit_core/*
  - packages/drivekit_trip_analysis/*
  - packages/drivekit_core/flutter_drivekit_core/example
  - packages/drivekit_trip_analysis/flutter_drivekit_trip_analysis/example

scripts:

  analyze:
    run: melos analyzeDart && melos analyzeNative
    description: Run analyzer in every packages

  analyzeDart:
    exec: |
      dart analyze --fatal-infos .
    description: Run analyzer in every Dart packages

  analyzeNative:
    run: |
      ./scripts/ktLintCheck.sh
    description: Run analyzer in every kotlin lib packages

  fix:
    exec: |
      dart fix . --apply && 
      dart format lib test
    description: Run fix in every packages

  test:
    exec: flutter test --no-pub --test-randomize-ordering-seed random
    description: Run test in every packages
    packageFilters:
      dirExists:
        - test
  test:cov:
    exec: |
      rm -rf coverage && \
      flutter test --coverage --no-pub --test-randomize-ordering-seed random && \
      remove_from_coverage -f coverage/lcov.info -r '\.g\.dart|\.freezed\.dart' && \
      genhtml coverage/lcov.info -o coverage 
    description: Run test with coverage in every packages
    packageFilters:
      dirExists:
        - test
  open:cov:
    exec: |
      open coverage/index.html
    description: Open test coverage in a package
    packageFilters:
      fileExists: "coverage/index.html"

  pigeon:
    exec: |
      dart run pigeon \
      --input pigeon/messages.dart \
    packageFilters:
      dirExists:
        - pigeon

    description: Generate pigeon code

  gen:core:
    description: Generate code in every packages from the last method in core platform interfaces
    run: |
      ./scripts/add_to_core.sh 
  gen:trip_analysis:
    description: Generate code in every packages from the last method in trip analysis platform interfaces
    run: |
      ./scripts/add_to_trip_analysis.sh 
