name: flutter_drivekit_core
description: Flutter plugin for DriveQuant's DriveKit core SDK
version: 0.0.2
homepage: https://www.drivequant.com/
repository: https://github.com/DriveQuantPublic/flutter-drivekit/tree/main/packages/drivekit_core/flutter_drivekit_core

environment:
  sdk: ^3.4.0
  flutter: '>=1.20.0'

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_drivekit_core_android
      ios:
        default_package: flutter_drivekit_core_ios

dependencies:
  flutter:
    sdk: flutter
  flutter_drivekit_core_android: ^0.0.2
  flutter_drivekit_core_ios: ^0.0.2
  flutter_drivekit_core_platform_interface: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
