name: flutter_drivekit_core
description: Flutter plugin for DriveQuant's DriveKit core SDK
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_drivekit_core_android
      ios:
        default_package: flutter_drivekit_core_ios

dependencies:
  flutter:
    sdk: flutter
  flutter_drivekit_core_android:
    path: ../flutter_drivekit_core_android
  flutter_drivekit_core_ios:
    path: ../flutter_drivekit_core_ios
  flutter_drivekit_core_platform_interface:
    path: ../flutter_drivekit_core_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
