import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_drivekit_core_android/src/adapter.dart';
import 'package:flutter_drivekit_core_android/src/core_api.g.dart';
import 'package:flutter_drivekit_core_android/src/model_adapter.dart';
import 'package:flutter_drivekit_core_platform_interface/flutter_drivekit_core_platform_interface.dart';

/// The Android implementation of [DriveKitCorePlatform].
class DriveKitCoreAndroid extends DriveKitCorePlatform
    implements FlutterCoreApi {
  /// Creates a new instance of [DriveKitCoreAndroid].
  /// The optional [androidCoreApi] parameter is used for
  /// dependency injection in tests.
  DriveKitCoreAndroid({AndroidCoreApi? androidCoreApi})
      : androidCoreApi = androidCoreApi ?? AndroidCoreApi();

  /// Registers this class as the default instance of [DriveKitCorePlatform]
  static void registerWith() {
    final instance = DriveKitCoreAndroid();
    DriveKitCorePlatform.instance = instance;
  }

  /// The instance of [AndroidCoreApi], a class that provides access to the
  /// native methods via a method channel generated by pigeon.
  @visibleForTesting
  final AndroidCoreApi androidCoreApi;

  @override
  void initializePlatform() {
    FlutterCoreApi.setUp(this);
  }

  final List<DriveKitListener> _driveKitListeners = [];

  final List<DKDeviceConfigurationListener> _deviceConfigurationListeners = [];

  @override
  Future<void> setApiKey(String key) => androidCoreApi.setApiKey(key);

  @override
  Future<void> setUserId(String userId) => androidCoreApi.setUserId(userId);

  @override
  Future<String?> getUserId() => androidCoreApi.getUserId();

  @override
  Future<void> updateUserId(String userId) =>
      androidCoreApi.updateUserId(userId);

  @override
  Future<void> reset() => androidCoreApi.reset();

  @override
  Future<bool> isTokenValid() => androidCoreApi.isTokenValid();

  @override
  Future<void> deleteAccount({bool instantDeletion = false}) =>
      androidCoreApi.deleteAccount(instantDeletion: instantDeletion);

  @override
  Future<String?> getApiKey() => androidCoreApi.getApiKey();

  @override
  Future<void> enableLogging({
    bool showInConsole = true,
    String androidLogPath = '/DriveKit',
  }) =>
      androidCoreApi.enableLogging(
        showInConsole: showInConsole,
        androidLogPath: androidLogPath,
      );

  @override
  Future<void> disableLogging({bool showInConsole = true}) =>
      androidCoreApi.disableLogging(showInConsole: showInConsole);

  @override
  void addDriveKitListener(DriveKitListener listener) {
    _driveKitListeners.add(listener);
  }

  @override
  void removeDriveKitListener(DriveKitListener listener) {
    _driveKitListeners.remove(listener);
  }

  @override
  void removeAllDriveKitListeners() {
    _driveKitListeners.clear();
  }

  @override
  void onConnected() {
    for (final listener in _driveKitListeners) {
      listener.onConnected?.call();
    }
  }

  @override
  void onAccountDeleted(PigeonDeleteAccountStatus status) {
    for (final listener in _driveKitListeners) {
      listener.onAccountDeleted?.call(status.toModelImplementation());
    }
  }

  @override
  void onAuthenticationError(PigeonRequestError errorType) {
    for (final listener in _driveKitListeners) {
      listener.onAuthenticationError?.call(errorType.toModelImplementation());
    }
  }

  @override
  void onDisconnected() {
    for (final listener in _driveKitListeners) {
      listener.onDisconnected?.call();
    }
  }

  @override
  void userIdUpdateStatus(
    PigeonUpdateUserIdStatus status,
    String? userId,
  ) {
    for (final listener in _driveKitListeners) {
      listener.userIdUpdateStatus?.call(status.toModelImplementation(), userId);
    }
  }

  @override
  Future<Uri?> getLogUriFile() async {
    final uriString = await androidCoreApi.getLogUriFile();
    if (uriString == null) {
      return null;
    } else {
      return Uri.parse(uriString);
    }
  }

  @override
  void addDeviceConfigurationListener(DKDeviceConfigurationListener listener) {
    _deviceConfigurationListeners.add(listener);
  }

  @override
  void removeDeviceConfigurationListener(
    DKDeviceConfigurationListener listener,
  ) {
    _deviceConfigurationListeners.remove(listener);
  }

  @override
  void removeAllDeviceConfigurationListeners() {
    _deviceConfigurationListeners.clear();
  }

  @override
  void onDeviceConfigurationChanged(PigeonDeviceConfigurationEvent event) {
    for (final listener in _deviceConfigurationListeners) {
      listener.onDeviceConfigurationChanged
          ?.call(event.toModelImplementation());
    }
  }

  @override
  Future<bool> updateUserInfo(UserInfo userInfo) =>
      androidCoreApi.updateUserInfo(userInfo.toPigeonImplementation());

  @override
  Future<GetUserInfoResponse> getUserInfo({
    SynchronizationType synchronizationType = SynchronizationType.defaultSync,
  }) async {
    final userInfo = await androidCoreApi.getUserInfo(
      synchronizationType: synchronizationType.toPigeonImplementation(),
    );
    return userInfo.toModelImplementation();
  }
}
