name: drivekit_trip_analysis_ios
description: iOS implementation of the drivekit_trip_analysis plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

flutter:
  plugin:
    implements: drivekit_trip_analysis
    platforms:
      ios:
        pluginClass: DrivekitTripAnalysisPlugin
        dartPluginClass: DrivekitTripAnalysisIOS

dependencies:
  drivekit_trip_analysis_platform_interface:
    path: ../drivekit_trip_analysis_platform_interface
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^20.0.2
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
