import 'package:drivekit_trip_analysis_android/src/trip_analysis_api.g.dart';
import 'package:drivekit_trip_analysis_platform_interface/drivekit_trip_analysis_platform_interface.dart';
import 'package:flutter/foundation.dart';

/// The Android implementation of [DrivekitTripAnalysisPlatform].
class DrivekitTripAnalysisAndroid extends DrivekitTripAnalysisPlatform {
  /// Creates a new instance of [DrivekitTripAnalysisAndroid].
  /// The optional [androidTripAnalysisApi] parameter is used for
  /// dependency injection in tests.
  DrivekitTripAnalysisAndroid({AndroidTripAnalysisApi? androidTripAnalysisApi})
      : androidTripAnalysisApi =
            androidTripAnalysisApi ?? AndroidTripAnalysisApi();

  /// Registers this class as the default instance of
  /// [DrivekitTripAnalysisPlatform]
  static void registerWith() {
    DrivekitTripAnalysisPlatform.instance = DrivekitTripAnalysisAndroid();
  }

  /// The instance of [AndroidTripAnalysisApi], a class that provides
  /// access to the native methods via a method channel generated by pigeon.
  @visibleForTesting
  final AndroidTripAnalysisApi androidTripAnalysisApi;

  @override
  Future<String> getPlatformName() => androidTripAnalysisApi.getPlatformName();
}
