name: flutter_drivekit_trip_analysis_android
description: Android implementation of the flutter_drivekit_trip_analysis plugin
version: 1.5.0
homepage: https://www.drivequant.com/
repository: https://github.com/DriveQuantPublic/flutter-drivekit/tree/main/packages/drivekit_trip_analysis/flutter_drivekit_trip_analysis_android

environment:
  sdk: ^3.4.0
  flutter: '>=1.20.0'

flutter:
  plugin:
    implements: flutter_drivekit_trip_analysis
    platforms:
      android:
        package: com.drivequant.drivekit.flutter.tripanalysis
        pluginClass: DriveKitTripAnalysisPlugin
        dartPluginClass: DriveKitTripAnalysisAndroid

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_drivekit_trip_analysis_platform_interface: 1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  pigeon: ^20.0.2
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
