import 'package:flutter/foundation.dart';
import 'package:flutter_drivekit_driver_data_ios/src/driver_data_api.g.dart';
import 'package:flutter_drivekit_driver_data_platform_interface/flutter_drivekit_driver_data_platform_interface.dart';

/// The iOS implementation of [DrivekitDriverDataPlatform].
class DrivekitDriverDataIOS extends DrivekitDriverDataPlatform {
  /// Creates a new instance of [DrivekitDriverDataIOS].
  /// The optional [iosDriverDataApi] parameter is used for
  /// dependency injection in tests.
  DrivekitDriverDataIOS({IOSDriverDataApi? iosDriverDataApi})
      : iosDriverDataApi = iosDriverDataApi ?? IOSDriverDataApi();

  /// Registers this class as the default instance of
  /// [DrivekitDriverDataPlatform]
  static void registerWith() {
    DrivekitDriverDataPlatform.instance = DrivekitDriverDataIOS();
  }

  /// The instance of [IOSDriverDataApi], a class that provides access to the
  /// native methods via a method channel generated by pigeon.
  @visibleForTesting
  final IOSDriverDataApi iosDriverDataApi;

  @override
  Future<String> getPlatformName() => iosDriverDataApi.getPlatformName();
  @override
  Future<bool> deleteTrip(String itinId) => iosDriverDataApi.deleteTrip(itinId);

  @override
  Future<GetTripsResponse> getTripsOrderByDateAsc() {
    // TODO: implement getTripsOrderByDateAsc
    throw UnimplementedError();
  }
}
