import 'package:flutter/foundation.dart';
import 'package:flutter_drivekit_driver_data_ios/src/adapter.dart';
import 'package:flutter_drivekit_driver_data_ios/src/driver_data_api.g.dart';
import 'package:flutter_drivekit_driver_data_ios/src/model_adapter.dart';
import 'package:flutter_drivekit_driver_data_platform_interface/flutter_drivekit_driver_data_platform_interface.dart';

/// The iOS implementation of [DrivekitDriverDataPlatform].
class DrivekitDriverDataIOS extends DrivekitDriverDataPlatform {
  /// Creates a new instance of [DrivekitDriverDataIOS].
  /// The optional [iosDriverDataApi] parameter is used for
  /// dependency injection in tests.
  DrivekitDriverDataIOS({IOSDriverDataApi? iosDriverDataApi})
      : iosDriverDataApi = iosDriverDataApi ?? IOSDriverDataApi();

  /// Registers this class as the default instance of
  /// [DrivekitDriverDataPlatform]
  static void registerWith() {
    DrivekitDriverDataPlatform.instance = DrivekitDriverDataIOS();
  }

  /// The instance of [IOSDriverDataApi], a class that provides access to the
  /// native methods via a method channel generated by pigeon.
  @visibleForTesting
  final IOSDriverDataApi iosDriverDataApi;

  @override
  Future<String> getPlatformName() => iosDriverDataApi.getPlatformName();

  @override
  Future<bool> deleteTrip(String itinId) => iosDriverDataApi.deleteTrip(itinId);

  @override
  Future<GetTripsResponse?> getTripsOrderByDateAsc({
    SynchronizationType synchronizationType = SynchronizationType.defaultSync,
    List<TransportationMode> transportationModes = const <TransportationMode>[],
  }) async {
    final trips = await iosDriverDataApi.getTripsOrderByDateAsc(
      synchronizationType: synchronizationType.toPigeonImplementation(),
      transportationModes: transportationModes
          .map((TransportationMode e) => e.toPigeonImplementation())
          .toList(),
    );
    return trips.toModelImplementation();
  }

  @override
  Future<GetTripsResponse?> getTripsOrderByDateDesc() async {
    final trips = await iosDriverDataApi.getTripsOrderByDateDesc();
    return trips.toModelImplementation();
  }
}
