name: flutter_drivekit_driver_data
description: This is the Flutter plugin for DriveQuant's DriveKit DriverData component.
version: 0.0.5
publish_to: none
homepage: https://www.drivequant.com/
repository: https://github.com/DriveQuantPublic/flutter-drivekit/tree/main/packages/drivekit_driver_data/flutter_drivekit_driver_data

environment:
  sdk: ^3.4.0
  flutter: '>=1.20.0'

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_drivekit_driver_data_android
      ios:
        default_package: flutter_drivekit_driver_data_ios

dependencies:
  flutter:
    sdk: flutter
  flutter_drivekit_driver_data_android: ^0.0.5
  flutter_drivekit_driver_data_ios: ^0.0.5
  flutter_drivekit_driver_data_platform_interface: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
