name: flutter_drivekit_trip_analysis_ios
description: iOS implementation of the flutter_drivekit_trip_analysis plugin
version: 1.2.2
homepage: https://www.drivequant.com/
repository: https://github.com/DriveQuantPublic/flutter-drivekit/tree/main/packages/drivekit_trip_analysis/flutter_drivekit_trip_analysis_ios

environment:
  sdk: ^3.4.0
  flutter: '>=1.20.0'

flutter:
  plugin:
    implements: flutter_drivekit_trip_analysis
    platforms:
      ios:
        pluginClass: DriveKitTripAnalysisPlugin
        dartPluginClass: DriveKitTripAnalysisIOS

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_drivekit_trip_analysis_platform_interface: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  pigeon: ^20.0.2
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
