name: flutter_drivekit_trip_analysis_ios
description: iOS implementation of the flutter_drivekit_trip_analysis plugin
version: 0.0.1

environment:
  sdk: ^3.4.0

flutter:
  plugin:
    implements: flutter_drivekit_trip_analysis
    platforms:
      ios:
        pluginClass: DrivekitTripAnalysisPlugin
        dartPluginClass: DrivekitTripAnalysisIOS

dependencies:
  flutter:
    sdk: flutter
  flutter_drivekit_trip_analysis_platform_interface: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  pigeon: ^20.0.2
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
