import 'package:flutter/foundation.dart';
import 'package:flutter_drivekit_trip_simulator_android/src/trip_simulator_api.g.dart';
import 'package:flutter_drivekit_trip_simulator_platform_interface/flutter_drivekit_trip_simulator_platform_interface.dart';

/// The Android implementation of [DrivekitTripSimulatorPlatform].
class DrivekitTripSimulatorAndroid extends DrivekitTripSimulatorPlatform {
  /// Creates a new instance of [DrivekitTripSimulatorAndroid].
  /// The optional [androidTripSimulatorApi] parameter is used for
  /// dependency injection in tests.
  DrivekitTripSimulatorAndroid({
    AndroidTripSimulatorApi? androidTripSimulatorApi,
  }) : androidTripSimulatorApi =
            androidTripSimulatorApi ?? AndroidTripSimulatorApi();

  /// Registers this class as the default instance of
  /// [DrivekitTripSimulatorPlatform]
  static void registerWith() {
    DrivekitTripSimulatorPlatform.instance = DrivekitTripSimulatorAndroid();
  }

  /// The instance of [AndroidTripSimulatorApi], a class that provides
  /// access to the native methods via a method channel generated by pigeon.
  @visibleForTesting
  final AndroidTripSimulatorApi androidTripSimulatorApi;

  @override
  Future<String> getPlatformName() => androidTripSimulatorApi.getPlatformName();
}
