#!/bin/bash

./scripts/add_to_public_package.sh \
./packages/drivekit_trip_simulator/flutter_drivekit_trip_simulator_platform_interface/lib/flutter_drivekit_trip_simulator_platform_interface.dart \
./packages/drivekit_trip_simulator/flutter_drivekit_trip_simulator/lib/flutter_drivekit_trip_simulator.dart \
DriveKitTripSimulatorPlatform \
DriveKitTripSimulator

./scripts/add_to_default_implem.sh \
./packages/drivekit_trip_simulator/flutter_drivekit_trip_simulator_platform_interface/lib/flutter_drivekit_trip_simulator_platform_interface.dart \
./packages/drivekit_trip_simulator/flutter_drivekit_trip_simulator_platform_interface/lib/src/default_drivekit_trip_simulator.dart \
DriveKitTripSimulatorPlatform \
DefaultDriveKitTripSimulator

./scripts/add_to_pigeon.sh \
./packages/drivekit_trip_simulator/flutter_drivekit_trip_simulator_platform_interface/lib/flutter_drivekit_trip_simulator_platform_interface.dart \
./packages/drivekit_trip_simulator/flutter_drivekit_trip_simulator_android/pigeon/messages.dart \
DriveKitTripSimulatorPlatform \
AndroidTripSimulatorApi

./scripts/add_to_pigeon.sh \
./packages/drivekit_trip_simulator/flutter_drivekit_trip_simulator_platform_interface/lib/flutter_drivekit_trip_simulator_platform_interface.dart \
./packages/drivekit_trip_simulator/flutter_drivekit_trip_simulator_ios/pigeon/messages.dart \
DriveKitTripSimulatorPlatform \
IOSTripSimulatorApi

melos pigeon

./scripts/add_to_platform_dart_file.sh \
./packages/drivekit_trip_simulator/flutter_drivekit_trip_simulator_platform_interface/lib/flutter_drivekit_trip_simulator_platform_interface.dart \
./packages/drivekit_trip_simulator/flutter_drivekit_trip_simulator_android/lib/flutter_drivekit_trip_simulator_android.dart \
DriveKitTripSimulatorPlatform \
DriveKitTripSimulatorAndroid \
androidTripSimulatorApi

./scripts/add_to_platform_dart_file.sh \
./packages/drivekit_trip_simulator/flutter_drivekit_trip_simulator_platform_interface/lib/flutter_drivekit_trip_simulator_platform_interface.dart \
./packages/drivekit_trip_simulator/flutter_drivekit_trip_simulator_ios/lib/flutter_drivekit_trip_simulator_ios.dart \
DriveKitTripSimulatorPlatform \
DriveKitTripSimulatorIOS \
iosTripSimulatorApi
