name: flutter_drivekit_core_android
description: Android implementation of the flutter_drivekit_core plugin
version: 0.0.1

environment:
  sdk: ^3.4.0

flutter:
  plugin:
    implements: flutter_drivekit_core
    platforms:
      android:
        package: com.drivequant.drivekit.flutter.core
        pluginClass: DrivekitCorePlugin
        dartPluginClass: DrivekitCoreAndroid

dependencies:
  flutter:
    sdk: flutter
  flutter_drivekit_core_platform_interface: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  pigeon: ^20.0.2
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
