name: flutter_drivekit_driver_data_platform_interface
description: A common platform interface for the flutter_drivekit_driver_data plugin.
version: 0.0.5
homepage: https://www.drivequant.com/
repository: https://github.com/DriveQuantPublic/flutter-drivekit/tree/main/packages/drivekit_driver_data/flutter_drivekit_driver_data_platform_interface

environment:
  sdk: ^3.4.0
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_drivekit_core_platform_interface: ^0.0.5
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
