import 'package:flutter/foundation.dart';
import 'package:flutter_drivekit_core_ios/src/adapter.dart';
import 'package:flutter_drivekit_core_ios/src/core_api.g.dart';
import 'package:flutter_drivekit_core_ios/src/model_adapter.dart';
import 'package:flutter_drivekit_core_platform_interface/flutter_drivekit_core_platform_interface.dart';

/// The iOS implementation of [DriveKitCorePlatform].
class DriveKitCoreIOS extends DriveKitCorePlatform implements FlutterCoreApi {
  /// Creates a new instance of [DriveKitCoreIOS].
  /// The optional [iosCoreApi] parameter is used for
  /// dependency injection in tests.
  DriveKitCoreIOS({IOSCoreApi? iosCoreApi})
      : iosCoreApi = iosCoreApi ?? IOSCoreApi();

  /// Registers this class as the default instance of [DriveKitCorePlatform]
  static void registerWith() {
    DriveKitCorePlatform.instance = DriveKitCoreIOS();
  }

  /// The instance of [IOSCoreApi], a class that provides access to the
  /// native methods via a method channel generated by pigeon.
  @visibleForTesting
  final IOSCoreApi iosCoreApi;

  // ensure the platform is initialized only once
  bool _isInitialized = false;

  @override
  void initializePlatform() {
    if (_isInitialized) return;
    FlutterCoreApi.setUp(this);
    _isInitialized = true;
  }

  final List<DriveKitListener> _driveKitListeners = [];

  final List<DKDeviceConfigurationListener> _deviceConfigurationListeners = [];

  @override
  Future<void> setApiKey(String key) => iosCoreApi.setApiKey(key);

  @override
  Future<void> setUserId(String userId) => iosCoreApi.setUserId(userId);

  @override
  Future<String?> getUserId() => iosCoreApi.getUserId();

  @override
  Future<void> updateUserId(String userId) => iosCoreApi.updateUserId(userId);

  @override
  Future<void> reset() => iosCoreApi.reset();

  @override
  Future<bool> isTokenValid() => iosCoreApi.isTokenValid();

  @override
  Future<void> deleteAccount({bool instantDeletion = false}) =>
      iosCoreApi.deleteAccount(instantDeletion: instantDeletion);
  @override
  Future<String?> getApiKey() => iosCoreApi.getApiKey();

  @override
  Future<void> enableLogging({
    bool showInConsole = true,
    String androidLogPath = '/DriveKit',
  }) =>
      iosCoreApi.enableLogging(showInConsole: showInConsole);

  @override
  Future<void> disableLogging({bool showInConsole = true}) =>
      iosCoreApi.disableLogging(showInConsole: showInConsole);

  @override
  void driveKitAccountDeletionCompleted(PigeonDeleteAccountStatus status) {
    for (final listener in _driveKitListeners) {
      listener.onAccountDeleted?.call(status.toModelImplementation());
    }
  }

  @override
  void driveKitBackgroundFetchStatusChanged(
    PigeonBackgroundFetchStatus status,
  ) {
    for (final listener in _driveKitListeners) {
      listener.onBackgroundFetchStatusChanged?.call(
        status.toModelImplementation(),
      );
    }
  }

  @override
  void driveKitDidConnect() {
    for (final listener in _driveKitListeners) {
      listener.onConnected?.call();
    }
  }

  @override
  void driveKitDidDisconnect() {
    for (final listener in _driveKitListeners) {
      listener.onDisconnected?.call();
    }
  }

  @override
  void driveKitDidReceiveAuthenticationError(PigeonRequestError error) {
    for (final listener in _driveKitListeners) {
      listener.onAuthenticationError?.call(error.toModelImplementation());
    }
  }

  @override
  void userIdUpdateStatusChanged(
    PigeonUpdateUserIdStatus status,
    String? userId,
  ) {
    for (final listener in _driveKitListeners) {
      listener.userIdUpdateStatus?.call(status.toModelImplementation(), userId);
    }
  }

  @override
  void addDriveKitListener(DriveKitListener listener) {
    _driveKitListeners.add(listener);
  }

  @override
  void removeDriveKitListener(DriveKitListener listener) {
    _driveKitListeners.remove(listener);
  }

  @override
  void removeAllDriveKitListeners() {
    _driveKitListeners.clear();
  }

  @override
  Future<Uri?> getLogUriFile() async {
    final uriString = await iosCoreApi.getLogUriFile();
    if (uriString == null) {
      return null;
    } else {
      return Uri.parse(uriString);
    }
  }

  @override
  void addDeviceConfigurationListener(DKDeviceConfigurationListener listener) {
    _deviceConfigurationListeners.add(listener);
  }

  @override
  void removeDeviceConfigurationListener(
    DKDeviceConfigurationListener listener,
  ) {
    _deviceConfigurationListeners.remove(listener);
  }

  @override
  void onDeviceConfigurationChanged(PigeonDeviceConfigurationEvent event) {
    for (final listener in _deviceConfigurationListeners) {
      listener.onDeviceConfigurationChanged
          ?.call(event.toModelImplementation());
    }
  }

  @override
  void removeAllDeviceConfigurationListeners() {
    _deviceConfigurationListeners.clear();
  }

  @override
  Future<bool> updateUserInfo(UserInfo userInfo) =>
      iosCoreApi.updateUserInfo(userInfo.toPigeonImplementation());

  @override
  Future<GetUserInfoResponse> getUserInfo({
    SynchronizationType synchronizationType = SynchronizationType.defaultSync,
  }) async {
    final userInfo = await iosCoreApi.getUserInfo(
      synchronizationType: synchronizationType.toPigeonImplementation(),
    );

    return userInfo.toModelImplementation();
  }
}
