name: Test

on:
  workflow_call:

jobs:
  test-dart:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - id: dotenv
        uses: falti/dotenv-action@v1.0.4
        with:
          path: .github/workflows/.env

      - name: 💙 Install Flutter
        uses: subosito/flutter-action@v2.9.1
        with:
          flutter-version: ${{ steps.dotenv.outputs.flutter_version }}
          channel: "stable"
          cache: true
          cache-key: ${{ runner.os }}-flutter-${{ steps.dotenv.outputs.flutter_version }}
          cache-path: ${{ runner.tool_cache }}/flutter-${{ steps.dotenv.outputs.flutter_version }}

      - name: 🟠 Install Dependencies
        uses: bluefireteam/melos-action@v1

      - name: ✅ Run tests
        run: melos test
