name: AnalyseSwift

on:
  workflow_call:
    
jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: SwiftLint core lib
        uses: norio-nomura/action-swiftlint@3.2.1
        env:
          WORKING_DIRECTORY: packages/drivekit_core/flutter_drivekit_core_ios/ios
